-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2025-02-17 12:22:10 EST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE droit (
    droit_id   NUMBER(255) NOT NULL,
    nom        VARCHAR2(255) NOT NULL,
    type_droit VARCHAR2(255) NOT NULL
);

ALTER TABLE droit ADD CONSTRAINT droit_pk PRIMARY KEY ( droit_id );

CREATE TABLE film_watchlist (
    film_id                    NUMBER(255) NOT NULL,
    utilisateur_utilisateur_id NUMBER(255) NOT NULL
);

CREATE UNIQUE INDEX film_watchlist__idx ON
    film_watchlist (
        utilisateur_utilisateur_id
    ASC );

ALTER TABLE film_watchlist ADD CONSTRAINT film_watchlist_pk PRIMARY KEY ( film_id );
ALTER TABLE note ADD UNIQUE unique_film_user (films_film_id, utilisateur_utilisateur_id);

CREATE TABLE films (
    film_id                NUMBER(255) NOT NULL,
    titre                  VARCHAR2(255) NOT NULL,
    film_duree             NUMBER(255) NOT NULL,
    date_sortie            DATE NOT NULL,
    pays_origin_film       VARCHAR2(255) NOT NULL,
    langue_original        VARCHAR2(255) NOT NULL,
    status                 VARCHAR2(255) NOT NULLNOT NULL
);

ALTER TABLE films ADD CONSTRAINT films_pk PRIMARY KEY ( film_id );

CREATE TABLE films_favoris (
    film_id                    NUMBER(255) NOT NULL,
    utilisateur_utilisateur_id NUMBER(255) NOT NULL
);

ALTER TABLE films_favoris ADD CONSTRAINT films_favoris_pk PRIMARY KEY ( film_id );

CREATE TABLE genre (
    genre_id      NUMBER(255) NOT NULL,
    genre         VARCHAR2(255) NOT NULL,
    films_film_id NUMBER(255) NOT NULL
);

ALTER TABLE genre ADD CONSTRAINT genre_pk PRIMARY KEY ( genre_id );

CREATE TABLE note (
    note_id                    NUMBER(255) NOT NULL,
    commentaire                VARCHAR2(255),
    valeur_note                NUMBER(255),
    films_film_id              NUMBER(255) NOT NULL,
    utilisateur_utilisateur_id NUMBER(255) NOT NULL
);

CREATE UNIQUE INDEX note__idx ON
    note (
        films_film_id
    ASC );

ALTER TABLE note ADD CONSTRAINT note_pk PRIMARY KEY ( note_id );

CREATE TABLE permission (
    permission_id              NUMBER(255) NOT NULL,
    note                       VARCHAR2(255) NOT NULL,
    utilisateur_utilisateur_id NUMBER(255) NOT NULL,
    droit_droit_id             NUMBER(255) NOT NULL
);

ALTER TABLE permission ADD CONSTRAINT permission_pk PRIMARY KEY ( permission_id );

CREATE TABLE "session" (
    session_id                 NUMBER(255) NOT NULL,
    date_cree                  DATE NOT NULL,
    jeton                      VARCHAR2(255) NOT NULL,
    utilisateur_utilisateur_id NUMBER(255) NOT NULL
);

ALTER TABLE "session" ADD CONSTRAINT session_pk PRIMARY KEY ( session_id );

CREATE TABLE utilisateur (
    utilisateur_id NUMBER(255) NOT NULL,
    nom            VARCHAR2(255) NOT NULL,
    prenom         VARCHAR2(255) NOT NULL,
    courriel       VARCHAR2(255) NOT NULL,
    mot_de_passe   VARCHAR2(255) NOT NULL,
    telephone      NUMBER(255) NOT NULL
);

ALTER TABLE utilisateur ADD CONSTRAINT utilisateur_pk PRIMARY KEY ( utilisateur_id );

ALTER TABLE film_watchlist
    ADD CONSTRAINT film_watchlist_utilisateur_fk FOREIGN KEY ( utilisateur_utilisateur_id )
        REFERENCES utilisateur ( utilisateur_id );

ALTER TABLE films_favoris
    ADD CONSTRAINT films_favoris_utilisateur_fk FOREIGN KEY ( utilisateur_utilisateur_id )
        REFERENCES utilisateur ( utilisateur_id );

ALTER TABLE genre
    ADD CONSTRAINT genre_films_fk FOREIGN KEY ( films_film_id )
        REFERENCES films ( film_id );

ALTER TABLE note
    ADD CONSTRAINT note_films_fk FOREIGN KEY ( films_film_id )
        REFERENCES films ( film_id );

ALTER TABLE note
    ADD CONSTRAINT note_utilisateur_fk FOREIGN KEY ( utilisateur_utilisateur_id )
        REFERENCES utilisateur ( utilisateur_id );

ALTER TABLE permission
    ADD CONSTRAINT permission_droit_fk FOREIGN KEY ( droit_droit_id )
        REFERENCES droit ( droit_id );

ALTER TABLE permission
    ADD CONSTRAINT permission_utilisateur_fk FOREIGN KEY ( utilisateur_utilisateur_id )
        REFERENCES utilisateur ( utilisateur_id );

ALTER TABLE "session"
    ADD CONSTRAINT session_utilisateur_fk FOREIGN KEY ( utilisateur_utilisateur_id )
        REFERENCES utilisateur ( utilisateur_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             2
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


-------------------------------------------------------------------------------------------------------------
---------------------SCRIPT----MYSQL-------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------

CREATE TABLE utilisateur (
    utilisateur_id INT NOT NULL AUTO_INCREMENT,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL,
    courriel VARCHAR(255) NOT NULL UNIQUE,
    mot_de_passe VARCHAR(255) NOT NULL,
    telephone VARCHAR(20) NOT NULL,
    PRIMARY KEY (utilisateur_id)
);

CREATE TABLE droit (
    droit_id INT NOT NULL AUTO_INCREMENT,
    nom VARCHAR(255) NOT NULL,
    type_droit VARCHAR(255) NOT NULL,
    PRIMARY KEY (droit_id)
);

CREATE TABLE films (
    film_id INT NOT NULL AUTO_INCREMENT,
    titre VARCHAR(255) NOT NULL,
    film_duree INT NOT NULL,
    date_sortie DATE NOT NULL,
    pays_origin_film VARCHAR(255) NOT NULL,
    langue_original VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    PRIMARY KEY (film_id)
);

CREATE TABLE genre (
    genre_id INT NOT NULL AUTO_INCREMENT,
    genre VARCHAR(255) NOT NULL,
    films_film_id INT NOT NULL,
    PRIMARY KEY (genre_id),
    FOREIGN KEY (films_film_id) REFERENCES films(film_id) ON DELETE CASCADE
);

CREATE TABLE note (
    note_id INT NOT NULL AUTO_INCREMENT,
    commentaire VARCHAR(255),
    valeur_note INT,
    films_film_id INT NOT NULL,
    utilisateur_utilisateur_id INT NOT NULL,
    PRIMARY KEY (note_id),
    UNIQUE KEY unique_user_movie (films_film_id, utilisateur_utilisateur_id),
    FOREIGN KEY (films_film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    FOREIGN KEY (utilisateur_utilisateur_id) REFERENCES utilisateur(utilisateur_id) ON DELETE CASCADE
);

CREATE TABLE permission (
    permission_id INT NOT NULL AUTO_INCREMENT,
    note VARCHAR(255) NOT NULL,
    utilisateur_utilisateur_id INT NOT NULL,
    droit_droit_id INT NOT NULL,
    PRIMARY KEY (permission_id),
    FOREIGN KEY (utilisateur_utilisateur_id) REFERENCES utilisateur(utilisateur_id) ON DELETE CASCADE,
    FOREIGN KEY (droit_droit_id) REFERENCES droit(droit_id) ON DELETE CASCADE
);

CREATE TABLE session (
    session_id INT NOT NULL AUTO_INCREMENT,
    date_cree DATE NOT NULL,
    jeton VARCHAR(255) NOT NULL,
    utilisateur_utilisateur_id INT NOT NULL,
    PRIMARY KEY (session_id),
    FOREIGN KEY (utilisateur_utilisateur_id) REFERENCES utilisateur(utilisateur_id) ON DELETE CASCADE
);

CREATE TABLE film_watchlist (
    film_id INT NOT NULL,
    utilisateur_utilisateur_id INT NOT NULL,
    PRIMARY KEY (film_id, utilisateur_utilisateur_id),
    FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    FOREIGN KEY (utilisateur_utilisateur_id) REFERENCES utilisateur(utilisateur_id) ON DELETE CASCADE
);

CREATE TABLE films_favoris (
    film_id INT NOT NULL,
    utilisateur_utilisateur_id INT NOT NULL,
    PRIMARY KEY (film_id, utilisateur_utilisateur_id),
    FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    FOREIGN KEY (utilisateur_utilisateur_id) REFERENCES utilisateur(utilisateur_id) ON DELETE CASCADE
);

-------------------------------------------------------------------------------------------------------------
---------------------INSERTION DES VALEURS DANS LES TABLES---------------------------------------------------
-------------------------------------------------------------------------------------------------------------
-- ================================
-- INSERT SAMPLE DATA
-- ================================
 
-- utilisateurs
INSERT INTO utilisateur (nom, prenom, courriel, mot_de_passe, telephone) VALUES
('Dupont', 'Alice',   'alice.dupont@example.com',   'password1', '514-123-0001'),
('Martin', 'Bob',     'bob.martin@example.com',     'password2', '514-123-0002'),
('Nguyen', 'Charlie', 'charlie.nguyen@example.com', 'password3', '514-123-0003');
 
-- droits
INSERT INTO droit (nom, type_droit) VALUES
('Administrateur', 'Admin'),
('Modérateur',     'Moderator'),
('Utilisateur',    'User');
 
-- films
INSERT INTO films (titre, film_duree, date_sortie, pays_origin_film, langue_original, status) VALUES
('Inception',       148, '2010-07-16', 'USA',        'English', 'released'),
('Parasite',        132, '2019-05-30', 'South Korea','Korean',  'released'),
('Avatar 3',        165, '2025-12-18', 'USA',        'English', 'upcoming'),
('Amélie',          122, '2001-04-25', 'France',     'French',  'released'),
('Spirited Away',   125, '2001-07-20', 'Japan',      'Japanese','released');
 
-- genres
INSERT INTO genre (genre, films_film_id) VALUES
('Sci-Fi',     1),
('Thriller',   1),
('Drama',      2),
('Sci-Fi',     3),
('Romance',    4),
('Animation',  5);
 
-- notes (avis utilisateurs)
INSERT INTO note (commentaire, valeur_note, films_film_id, utilisateur_utilisateur_id) VALUES
('Mind-bending and thrilling', 5, 1, 1),
('Très bien réalisé',           4, 2, 2),
('Impatient to see it!',       5, 3, 1),
('Un classique charmant',       5, 4, 3),
('Great visuals, good story',  4, 1, 2);
 
-- permissions
INSERT INTO permission (note, utilisateur_utilisateur_id, droit_droit_id) VALUES
('Granted full access', 1, 1),
('Moderator access',    3, 2),
('Regular user',        2, 3);
 
-- sessions
INSERT INTO session (date_cree, jeton, utilisateur_utilisateur_id) VALUES
('2025-05-17', 'token_abc123', 1),
('2025-05-16', 'token_def456', 2),
('2025-05-15', 'token_ghi789', 3);
 
-- watchlists
INSERT INTO film_watchlist (film_id, utilisateur_utilisateur_id) VALUES
(2, 1),
(3, 1),
(1, 2),
(1, 3),
(4, 3);
 
-- favoris
INSERT INTO films_favoris (film_id, utilisateur_utilisateur_id) VALUES
(1, 1),
(2, 2),
(5, 3);
