-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2025-02-17 12:22:10 EST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE droit (
    droit_id   NUMBER(255) NOT NULL,
    nom        VARCHAR2(255) NOT NULL,
    type_droit VARCHAR2(255) NOT NULL
);

ALTER TABLE droit ADD CONSTRAINT droit_pk PRIMARY KEY ( droit_id );

CREATE TABLE film_watchlist (
    film_id                    NUMBER(255) NOT NULL,
    utilisateur_utilisateur_id NUMBER(255) NOT NULL
);

CREATE UNIQUE INDEX film_watchlist__idx ON
    film_watchlist (
        utilisateur_utilisateur_id
    ASC );

ALTER TABLE film_watchlist ADD CONSTRAINT film_watchlist_pk PRIMARY KEY ( film_id );
ALTER TABLE note ADD UNIQUE unique_film_user (films_film_id, utilisateur_utilisateur_id);

CREATE TABLE films (
    film_id                NUMBER(255) NOT NULL,
    titre                  VARCHAR2(255) NOT NULL,
    film_duree             NUMBER(255) NOT NULL,
    date_sortie            DATE NOT NULL,
    pays_origin_film       VARCHAR2(255) NOT NULL,
    langue_original        VARCHAR2(255) NOT NULL,
    status                 VARCHAR2(255) NOT NULLNOT NULL
);

ALTER TABLE films ADD CONSTRAINT films_pk PRIMARY KEY ( film_id );

CREATE TABLE films_favoris (
    film_id                    NUMBER(255) NOT NULL,
    utilisateur_utilisateur_id NUMBER(255) NOT NULL
);

ALTER TABLE films_favoris ADD CONSTRAINT films_favoris_pk PRIMARY KEY ( film_id );

CREATE TABLE genre (
    genre_id      NUMBER(255) NOT NULL,
    genre         VARCHAR2(255) NOT NULL,
    films_film_id NUMBER(255) NOT NULL
);

ALTER TABLE genre ADD CONSTRAINT genre_pk PRIMARY KEY ( genre_id );

CREATE TABLE note (
    note_id                    NUMBER(255) NOT NULL,
    commentaire                VARCHAR2(255),
    valeur_note                NUMBER(255),
    films_film_id              NUMBER(255) NOT NULL,
    utilisateur_utilisateur_id NUMBER(255) NOT NULL
);

CREATE UNIQUE INDEX note__idx ON
    note (
        films_film_id
    ASC );

ALTER TABLE note ADD CONSTRAINT note_pk PRIMARY KEY ( note_id );

CREATE TABLE permission (
    permission_id              NUMBER(255) NOT NULL,
    note                       VARCHAR2(255) NOT NULL,
    utilisateur_utilisateur_id NUMBER(255) NOT NULL,
    droit_droit_id             NUMBER(255) NOT NULL
);

ALTER TABLE permission ADD CONSTRAINT permission_pk PRIMARY KEY ( permission_id );

CREATE TABLE "session" (
    session_id                 NUMBER(255) NOT NULL,
    date_cree                  DATE NOT NULL,
    jeton                      VARCHAR2(255) NOT NULL,
    utilisateur_utilisateur_id NUMBER(255) NOT NULL
);

ALTER TABLE "session" ADD CONSTRAINT session_pk PRIMARY KEY ( session_id );

CREATE TABLE utilisateur (
    utilisateur_id NUMBER(255) NOT NULL,
    nom            VARCHAR2(255) NOT NULL,
    prenom         VARCHAR2(255) NOT NULL,
    courriel       VARCHAR2(255) NOT NULL,
    mot_de_passe   VARCHAR2(255) NOT NULL,
    telephone      NUMBER(255) NOT NULL
);

ALTER TABLE utilisateur ADD CONSTRAINT utilisateur_pk PRIMARY KEY ( utilisateur_id );

ALTER TABLE film_watchlist
    ADD CONSTRAINT film_watchlist_utilisateur_fk FOREIGN KEY ( utilisateur_utilisateur_id )
        REFERENCES utilisateur ( utilisateur_id );

ALTER TABLE films_favoris
    ADD CONSTRAINT films_favoris_utilisateur_fk FOREIGN KEY ( utilisateur_utilisateur_id )
        REFERENCES utilisateur ( utilisateur_id );

ALTER TABLE genre
    ADD CONSTRAINT genre_films_fk FOREIGN KEY ( films_film_id )
        REFERENCES films ( film_id );

ALTER TABLE note
    ADD CONSTRAINT note_films_fk FOREIGN KEY ( films_film_id )
        REFERENCES films ( film_id );

ALTER TABLE note
    ADD CONSTRAINT note_utilisateur_fk FOREIGN KEY ( utilisateur_utilisateur_id )
        REFERENCES utilisateur ( utilisateur_id );

ALTER TABLE permission
    ADD CONSTRAINT permission_droit_fk FOREIGN KEY ( droit_droit_id )
        REFERENCES droit ( droit_id );

ALTER TABLE permission
    ADD CONSTRAINT permission_utilisateur_fk FOREIGN KEY ( utilisateur_utilisateur_id )
        REFERENCES utilisateur ( utilisateur_id );

ALTER TABLE "session"
    ADD CONSTRAINT session_utilisateur_fk FOREIGN KEY ( utilisateur_utilisateur_id )
        REFERENCES utilisateur ( utilisateur_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             2
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


-------------------------------------------------------------------------------------------------------------
---------------------SCRIPT----MYSQL-------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------


CREATE TABLE utilisateur (
    utilisateur_id INT NOT NULL AUTO_INCREMENT,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL,
    courriel VARCHAR(255) NOT NULL UNIQUE,
    mot_de_passe VARCHAR(255) NOT NULL,
    telephone VARCHAR(20) NOT NULL,
    PRIMARY KEY (utilisateur_id)
);

CREATE TABLE droit (
    droit_id INT NOT NULL AUTO_INCREMENT,
    nom VARCHAR(255) NOT NULL,
    type_droit VARCHAR(255) NOT NULL,
    PRIMARY KEY (droit_id)
);

CREATE TABLE films (
    film_id INT NOT NULL AUTO_INCREMENT,
    titre VARCHAR(255) NOT NULL,
    film_duree INT NOT NULL,
    date_sortie DATE NOT NULL,
    pays_origin_film VARCHAR(255) NOT NULL,
    langue_original VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL
    PRIMARY KEY (film_id),
    );


CREATE TABLE genre (
    genre_id INT NOT NULL AUTO_INCREMENT,
    genre VARCHAR(255) NOT NULL,
    films_film_id INT NOT NULL,
    PRIMARY KEY (genre_id),
    FOREIGN KEY (films_film_id) REFERENCES films(film_id) ON DELETE CASCADE
);

CREATE TABLE note (
    note_id INT NOT NULL AUTO_INCREMENT,
    commentaire VARCHAR(255),
    valeur_note INT,
    films_film_id INT NOT NULL,
    utilisateur_utilisateur_id INT NOT NULL,
    PRIMARY KEY (note_id),
    UNIQUE KEY unique_user_movie (films_film_id, utilisateur_utilisateur_id),
    FOREIGN KEY (films_film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    FOREIGN KEY (utilisateur_utilisateur_id) REFERENCES utilisateur(utilisateur_id) ON DELETE CASCADE
);


CREATE TABLE permission (
    permission_id INT NOT NULL AUTO_INCREMENT,
    note VARCHAR(255) NOT NULL,
    utilisateur_utilisateur_id INT NOT NULL,
    droit_droit_id INT NOT NULL,
    PRIMARY KEY (permission_id),
    FOREIGN KEY (utilisateur_utilisateur_id) REFERENCES utilisateur(utilisateur_id) ON DELETE CASCADE,
    FOREIGN KEY (droit_droit_id) REFERENCES droit(droit_id) ON DELETE CASCADE
);

CREATE TABLE session (
    session_id INT NOT NULL AUTO_INCREMENT,
    date_cree DATE NOT NULL,
    jeton VARCHAR(255) NOT NULL,
    utilisateur_utilisateur_id INT NOT NULL,
    PRIMARY KEY (session_id),
    FOREIGN KEY (utilisateur_utilisateur_id) REFERENCES utilisateur(utilisateur_id) ON DELETE CASCADE
);

CREATE TABLE film_watchlist (
    film_id INT NOT NULL,
    utilisateur_utilisateur_id INT NOT NULL,
    PRIMARY KEY (film_id, utilisateur_utilisateur_id),
    FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    FOREIGN KEY (utilisateur_utilisateur_id) REFERENCES utilisateur(utilisateur_id) ON DELETE CASCADE
);

CREATE TABLE films_favoris (
    film_id INT NOT NULL,
    utilisateur_utilisateur_id INT NOT NULL,
    PRIMARY KEY (film_id, utilisateur_utilisateur_id),
    FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE,
    FOREIGN KEY (utilisateur_utilisateur_id) REFERENCES utilisateur(utilisateur_id) ON DELETE CASCADE
);
ALTER TABLE films_favoris 
ADD CONSTRAINT films_favoris_utilisateur_fk 
FOREIGN KEY (utilisateur_utilisateur_id) 
REFERENCES utilisateur(utilisateur_id) ON DELETE CASCADE;




-------------------------------------------------------------------------------------------------------------
---------------------INSERTION DES VALEURS DANS LES TABLES---------------------------------------------------
-------------------------------------------------------------------------------------------------------------

INSERT INTO utilisateur (nom, prenom, courriel, mot_de_passe, telephone) VALUES 
('Doe', 'John', 'john.doe@example.com', 'password123', '1234567890'), 
('Smith', 'Jane', 'jane.smith@example.com', 'securepass', '0987654321');

INSERT INTO droit (nom, type_droit) VALUES 
('Admin', 'Full Access'), 
('User', 'Read Only');

INSERT INTO films (titre, film_duree, date_sortie, pays_origin_film, langue_original, status) VALUES 
('Inception', 148, '2010-07-16', 'États-Unis', 'Anglais', 'Vu', 1), 
('Pulp Fiction', 154, '1994-10-14', 'États-Unis', 'Anglais', 'Non vu');

INSERT INTO genre (genre, films_film_id) VALUES 
('Science Fiction', 1), 
('Crime', 2);

INSERT INTO note (commentaire, valeur_note, films_film_id, utilisateur_utilisateur_id) VALUES 
('Amazing movie!', 5, 1, 1), 
('Classic film!', 4, 2, 2);

INSERT INTO permission (note, utilisateur_utilisateur_id, droit_droit_id) VALUES 
('Full control', 1, 1), 
('Limited access', 2, 2);

INSERT INTO session (date_cree, jeton, utilisateur_utilisateur_id) VALUES 
('2025-02-24', 'abc123token', 1), 
('2025-02-24', 'xyz789token', 2);

INSERT INTO film_watchlist (film_id, utilisateur_utilisateur_id) VALUES 
(1, 1), 
(2, 2);

INSERT INTO films_favoris (film_id, utilisateur_utilisateur_id) VALUES 
(1, 1), 
(2, 2);

INSERT INTO films (film_id, titre, film_duree, date_sortie, pays_origin_film, langue_original, status)
VALUES
(3, 'The Dark Knight', 152, '2008-07-18', 'USA', 'English', 'vu', 1),
(4, 'Interstellar', 169, '2014-11-07', 'USA', 'English', 'vu', 2),
(5, 'Inception', 148, '2010-07-16', 'USA', 'English', 'vu', 2),
(6, 'Titanic', 195, '1997-12-19', 'USA', 'English', 'non vu', 1),
(7, 'The Godfather', 175, '1972-03-24', 'USA', 'English', 'vu', 2),
(8, 'Pulp Fiction', 154, '1994-10-14', 'USA', 'English', 'vu', 2),
(9, 'Fight Club', 139, '1999-10-15', 'USA', 'English', 'non vu', 1),
(10, 'Forrest Gump', 142, '1994-07-06', 'USA', 'English', 'vu', 1),
(11, 'The Matrix', 136, '1999-03-31', 'USA', 'English', 'vu', 2),
(12, 'The Lord of the Rings: The Fellowship of the Ring', 178, '2001-12-19', 'New Zealand', 'English', 'vu', 2),
(13, 'The Lord of the Rings: The Two Towers', 179, '2002-12-18', 'New Zealand', 'English', 'vu', 1),
(14, 'The Lord of the Rings: The Return of the King', 201, '2003-12-17', 'New Zealand', 'English', 'vu', 1),
(15, 'The Shawshank Redemption', 142, '1994-09-23', 'USA', 'English', 'vu', 1),
(16, 'Gladiator', 155, '2000-05-05', 'USA', 'English', 'non vu', 1),
(17, 'The Avengers', 143, '2012-04-25', 'USA', 'English', 'vu', 1),
(18, 'Avatar', 162, '2009-12-18', 'USA', 'English', 'vu', 1),
(19, 'Joker', 122, '2019-10-04', 'USA', 'English', 'vu', 1),
(20, 'Spider-Man: No Way Home', 148, '2021-12-17', 'USA', 'English', 'vu', 1),
(21, 'Django Unchained', 165, '2012-12-25', 'USA', 'English', 'non vu', 2),
(22, 'The Wolf of Wall Street', 180, '2013-12-25', 'USA', 'English', 'vu');
